var EIGHT = '1/8';
var SIXTEEN = '1/16';
var SIXTEEN3 = '3/16';
var THREEOLE = '1/12'
var FIGURES = {
	f1: [EIGHT, EIGHT],
	f2: [SIXTEEN, SIXTEEN3],
	f3: [SIXTEEN3, SIXTEEN],
	f4: [SIXTEEN, SIXTEEN, EIGHT],
	f5: [EIGHT, SIXTEEN, SIXTEEN],
	f6: [SIXTEEN, EIGHT, SIXTEEN],
	f7: [THREEOLE, THREEOLE, THREEOLE]
};
var DURATIONS = {
	[EIGHT]: 1 / 8,
	[SIXTEEN]: 1 / 16,
	[SIXTEEN3]: 3 / 16,
	[THREEOLE]: 1 / 12
};

module.exports = {EIGHT, SIXTEEN, SIXTEEN3, THREEOLE, FIGURES, DURATIONS};
